# 載入numpy套件

In [ ]:
#載入numpy套件
import numpy as np

#根據列表建立ndarray(N-dimontional-array)物件
ndarr = np.array([3,4,-5])

#簡單的觀察
print(ndarr) #把物件中的資料印出來
print(ndarr.size) #取得資料的數量

[ 3  4 -5]
3


## 建立陣列

In [ ]:
import numpy as np

#建立一維陣列
# data = np.array([3,2,6,4])
# print(data)
# data = np.empty(4) #創造一個有四個資料的一維陣列,資料未指定
# print(data)
# data = np.zeros(3) #創造一個有三個(資料為0)的一維陣列
# print(data)
# data = np.ones(3)
# print(data)
data = np.arange(-5, 5 ,0.5) #每0.5取一次
print(data)

#建立二維陣列
# data = np.array([
#                  [2,3,2],
#                  [1,2,5],
#                  [3,5,7] 
#          ])   3x3
# print(data)
# data = np.empty([3,3]) #創造一個3x3的二維陣列,資料未指定
# print(data)
# data = np.zeros([2,3]) #[[0. 0. 0.][0. 0. 0.]]
# print(data)
# data = np.ones([5,2])
# print(data)

#建立多維陣列
# data = np.array([
#                  [
#                   [
#                    [2,2],[3,3]
#                   ]
#                  ]
#          ])                #建立一個1x1x2x2的四維陣列
# print(data.shape)
# data = np.empty([2,2,2,2])
# print(data)
# data = np.zeros([2,2,2,2])
# print(data)
# data = np.ones([1,1,3,4])
# print(data)


[-5.  -4.5 -4.  -3.5 -3.  -2.5 -2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5
  2.   2.5  3.   3.5  4.   4.5]
[[0. 0. 0.]
 [0. 0. 0.]]


## 陣列資料型別

In [ ]:
'''
Items data type
'''
arr = np.array([1.1, 2.1, 3.1])
print(arr.dtype)
newarr = arr.astype('int')
print(newarr)
print(newarr.dtype)

float64
[1 2 3]
int64


## Numpy運算

In [ ]:
import numpy as np

#逐元運算(elementwise)
data1 = np.array([3,2,10])
data2 = np.array([1,3,6])
# result=data1+data2
# print("加法",result)
# result=data1*data2
# print("乘法",result)
# result=data1>data2
# print("大於",result)
# result = data1==data2
# print("是否相等",result)

#矩陣運算(matrix)
# data1 = np.array([[1,3]]) #1x2
# data2 = np.array([[2,-1,3],[-2,4,1]]) #2x3
# result=data1.dot(data2) #1x3 or data1@data2
# print("內積",result)
# result = np.outer(data1,data2) #2x6
# print("外積",result)

#統計運算(statistics)
data=np.array([[2,1,7],[-5,3,8]]) #2x3
# result=data.cumsum() #逐個累加2,2+1,2+1+7,brabra
# print(result)
result=data.sum(axis=0) #針對column做總和 axis=1針對row做總和
print(result)
# result=data.sum(axis=1)
# print(result)
# result=data.max(axis=0)
# print(result)
# result=data.mean(axis=1)
# print(result)
# result=data.sum()
# print("總和",result)
# result=data.max()
# print("最大值",result)
# result=data.mean()
# print("平均數",result)
# result=data.std()
# print("標準差",result)


[-3  4 15]


## 多維陣列維度/形狀操作

In [ ]:
import numpy as np

#觀察資料形狀
# data = np.ones(10)
# print(data.shape)  #(10,)
# data = np.array([[[1,3,6],[5,4,6]]])
# print(data.shape)

#資料轉置 by T
# data = np.array([[5,3,6],[5,4,6]])
# print(data.shape)
# print(data.T.shape) 

#扁平化資料
# data = np.array([[[2,1,3],[1,2,3]],[[4,5,6],[8,9,10]]])
# print(data.shape)
# newdata=data.ravel()
# print(newdata)
# print(newdata.shape)

#重朔資料形狀
# data = np.array([[[2,1,3],[1,2,3]],[[4,5,6],[8,9,10]]]) #2x2x3=12
# newdata = data.reshape(3,4) #3x4=12
# print(newdata)
# newdata = data.reshape(4,3,1) #4x3x1=12
# print(newdata)

# data = np.zeros(18).reshape(3,6)
# print(data)

#產生1個3X3且數字0~9的矩陣
data=np.arange(9).reshape(3,3)
print(data)
print(data.T)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]


## 多維陣列的索引 Indexing

In [ ]:
import numpy as np


#單維度的資料
# data=np.array([1,5,2,10])
# print(data[1])

#多維度的資料
# data=np.array([[1,5],[2,6],[4,6]]) #3x2
# print(data[0,1]) #5
# print(data[1,0]) #2
# print(data[2,0]) #4

#多維陣列的切片
#單維度的切片
# data=np.array([-1,-5,2,3])
# print(data[0:3]) #[-1 -5  2]
# print(data[:2])  #[-1 -5]

#多維度的切片
# data=np.array([[0,1,2],[3,4,5],[5,4,3],[2,1,0]]) #4x3
# print(data[1:3,0:2]) #[3,4][5,4]
# print(data[0:2,1])  #[1 4]

#使用...代表我全都要
data=np.array([
              [
                [8,1,3],[-5,5,2]
              ],
              [
                [0,1,6],[4,4,-3]
              ]
       ]) #2x2x3
print(data.shape)
print(data[0,...])
print("====")
print(data[..., 1:3])

(2, 2, 3)
[[ 8  1  3]
 [-5  5  2]]
====
[[[ 1  3]
  [ 5  2]]

 [[ 1  6]
  [ 4 -3]]]


In [ ]:
'''
Iterate array item + index
'''
arr = np.array([1, 2, 5])
for idx, x in np.ndenumerate(arr):
    print(idx, x)
    
for idx, x in enumerate(arr):
    print(idx, x)
    
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]]) #2X4
for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0,) 1
(1,) 2
(2,) 5
0 1
1 2
2 5
(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


## 陣列連接

In [ ]:
'''
Concatenate
'''

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)
print(arr1.tolist() + arr2.tolist())

[1 2 3 4 5 6]
[1, 2, 3, 4, 5, 6]


## 陣列合併

In [ ]:
import numpy as np

#準備測試資料
arr1 = np.array([ [1,2,3] , [4,5,6] ]) #2x3
arr2 = np.array([ [7,8,9] , [10,11,12] ]) #2x3
arr3 = np.array([[13,14],[15,16]]) #2x2

#合併第一個維度
# result1=np.vstack((arr1, arr2))
# print(result1)
"""
  4x3 [[123],[456],[789],[101112]]
"""

#合併第二格維度
# result2=np.hstack((arr1,arr2))
# print(result2)
"""
  2x6 [[1 2 3 7 8 9],[4 5 6 10 11 12]]
"""
result3=np.hstack((arr1,arr2,arr3))
print(result3) #2x(3+3+2)



[[ 1  2  3  7  8  9 13 14]
 [ 4  5  6 10 11 12 15 16]]


## 陣列切割

In [ ]:
import numpy as np

#準備測試資料
arr=np.array([[2,4,6,8,10,12],[1,3,5,7,9,11]]) #2x6

#根據第一個維度切割
# result1=np.vsplit(arr,2)
# print(result1)
"[2,4,6,8,10,12] 1X6"
"[1,3,5,7,9,11] 1X6"

#根據地二個維度切割
# result2=np.hsplit(arr,2)
# print(result2)
"2x3 [[2,4,6],[1,3,5]]"
"2x3 [[8,10,12],[7,9,11]]"

#根據地二個維度切割成3個陣列
result=np.hsplit(arr,3)
print(result)
"2x2 [[2,4],[1,3]]"
"2x2 [[6,8],[5,7]]"
"2x2 [[10,12],[9,11]]"

[array([[2, 4],
       [1, 3]]), array([[6, 8],
       [5, 7]]), array([[10, 12],
       [ 9, 11]])]


'2x2 [[10,12],[9,11]]'

## 多維度的切片

In [ ]:
import numpy as np

# data=np.array([[0,1,2],[3,4,5],[5,4,3],[2,1,0]]) #4x3
# print(data[1:3,0:2]) 
# print(data[0:2,1]) #[1 4]

#使用...代表我全都要
data=np.array([
              [
                [8,1,3],[-5,5,2]
              ],
              [
                [0,1,6],[4,4,-3]
              ]
       ]) #2x2x3
print(data.shape)
print(data[0,...])
print("="*60)
print(data[... ,1:3])
print("="*60)

data=np.array([
               [
                [1,2,3],[4,5,6],[7,8,9]
               ],
               [
                   [1,2,3],[4,5,6],[7,8,9]
               ],
               [
                [1,2,3],[4,5,6],[7,8,9]
               ]
        ])  #3x3x3
print(data.shape)
print(data)

(2, 2, 3)
[[ 8  1  3]
 [-5  5  2]]
[[[ 1  3]
  [ 5  2]]

 [[ 1  6]
  [ 4 -3]]]
(3, 3, 3)
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


## where 函數 找出函數index

In [ ]:
'''
where()
search an array for a certain value, 
and return the indexes that get a match.
'''

arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 1)
print(x) 
print(arr[x])

In [16]:
import numpy as np
x = np.array([1,2,3,4,5,6,7,8])
x = x.reshape(2,4)
y = np.expand_dims(x,axis=2)
print(x.shape,y.shape)
print(y)

(2, 4) (2, 4, 1)
[[[1]
  [2]
  [3]
  [4]]

 [[5]
  [6]
  [7]
  [8]]]
